version: '3'

services:
  snyk_broker:
    image: "snyk/broker:gitlab"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment: 
      - BROKER_TOKEN=
      - LOG_LEVEL=info
#      - ACCEPT=/app/accept.json
      - GITLAB_TOKEN=
      - GITLAB=gitlab.com
      - BROKER_CLIENT_URL=http://broker.url:8000
      - PORT=8000
