version: '3'

services:
  snyk_broker_bitbucket-dc:
    image: "snyk/broker:bitbucket-server"
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    environment: 
      - BROKER_TOKEN=
      - LOG_LEVEL=info
      - ACCEPT=/app/accept.json
      - BITBUCKET_USERNAME=
      - BITBUCKET_PASSWORD=
      - BITBUCKET=bitbucket-loadbala-1hoodmaa1al0v-1781514605.us-east-1.elb.amazonaws.com
      - BITBUCKET_API=bitbucket-loadbala-1hoodmaa1al0v-1781514605.us-east-1.elb.amazonaws.com/rest/api/1.0
      - BROKER_CLIENT_URL=http://broker-bitbucket-dc.ss.snyk.app:8002
      - PORT=8002
